## IDN

In [1]:
import os, re, json, math, pdfplumber, torch, csv
from pathlib import Path
from tqdm import tqdm
from transformers import AutoTokenizer, AutoModelForSequenceClassification

MODEL_NAME = "facebook/bart-large-mnli"
device     = torch.device("cuda" if torch.cuda.is_available() else "cpu")
tokenizer  = AutoTokenizer.from_pretrained(MODEL_NAME)
model      = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME).to(device)
label2id   = {v.lower(): k for k, v in model.config.id2label.items()}

In [ ]:
import re
import csv
import json
import torch
import pdfplumber
from tqdm import tqdm
from pathlib import Path

def extract_pdf(path: str) -> str:
    text = []
    with pdfplumber.open(path) as pdf:
        for p in pdf.pages:
            page = p.extract_text() or ""
            text.append(page)
    return re.sub(r"\s+", " ", " ".join(text)).strip()


def chunk_text(txt: str, max_tokens: int = 256, overlap: int = 64):
    words = txt.split()
    step = max_tokens - overlap
    for i in range(0, len(words), step):
        yield " ".join(words[i:i + max_tokens])


@torch.inference_mode()
def nli_score(premise_chunks, hypothesis: str):
    max_scores = {"entailment": 0.0, "neutral": 0.0, "contradiction": 0.0}
    for prem in premise_chunks:
        enc = tokenizer(prem, hypothesis, truncation=True, return_tensors="pt").to(device)
        logits = model(**enc).logits
        probs = torch.softmax(logits, -1)[0]
        max_scores["entailment"] = max(max_scores["entailment"], probs[label2id["entailment"]].item())
        max_scores["neutral"] = max(max_scores["neutral"], probs[label2id["neutral"]].item())
        max_scores["contradiction"] = max(max_scores["contradiction"], probs[label2id["contradiction"]].item())
    return max_scores


def extract_range(filename):
    match = re.search(r"(\d{1,3}-\d{1,3})", filename)
    return match.group(1) if match else None


def process_all(doc_dir: str, json_dir: str, output_score: str):
    doc_dir = Path(doc_dir)
    json_dir = Path(json_dir)
    output_score = Path(output_score)
    output_score.mkdir(parents=True, exist_ok=True)

    # Loop per subdirektori (contoh D1-xxx)
    for doc_subdir in sorted(doc_dir.iterdir()):
        if not doc_subdir.is_dir():
            continue

        dir_prefix = doc_subdir.name.split("-")[0]  # contoh: D3
        json_subdir = next((d for d in json_dir.iterdir() if d.name.startswith(dir_prefix)), None)

        if not json_subdir:
            print(f"Skip: Tidak ditemukan pasangan untuk {doc_subdir.name}!!")
            continue

        print(f"\n=== Memproses direktori: {doc_subdir.name} ===")

        results = []
        pdf_files = list(doc_subdir.glob("*.pdf"))
        json_files = list(json_subdir.glob("*.json"))

        json_map = {extract_range(f.name): f for f in json_files if extract_range(f.name)}

        for pdf_path in tqdm(pdf_files, desc=f"Proses {doc_subdir.name}"):
            range_key = extract_range(pdf_path.name)
            if not range_key or range_key not in json_map:
                print(f" Skip: {pdf_path.name} tidak ada pasangan JSON yang cocok")
                continue

            json_path = json_map[range_key]
            try:
                premise = extract_pdf(str(pdf_path))
                premise_chunks = list(chunk_text(premise))

                qna_data = json.loads(json_path.read_text(encoding="utf-8"))
                source = "grok" if "grok" in json_path.name.lower() else "gpt"

                for item in qna_data:
                    question = item.get("Question", "").strip()
                    answer = item.get("Answer", "").strip()
                    hypothesis = answer or f"{question} {answer}".strip()
                    scores = nli_score(premise_chunks, hypothesis)

                    results.append({
                        "file": pdf_path.stem,
                        "generator": source,
                        "question": question,
                        "answer": answer,
                        "score_entailment": round(scores["entailment"], 4),
                        "score_neutral": round(scores["neutral"], 4),
                        "score_contradiction": round(scores["contradiction"], 4),
                        "score_final": round(scores["entailment"] - scores["contradiction"], 4),
                    })
            except Exception as e:
                print(f"Gagal memproses {pdf_path.name}: {e}")

        output_csv = output_score / f"{doc_subdir.name}.csv"
        with open(output_csv, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=[
                "file", "generator", "question", "answer",
                "score_entailment", "score_neutral", "score_contradiction", "score_final"
            ], delimiter=";")
            writer.writeheader()
            writer.writerows(results)

        print(f"Selesai: {doc_subdir.name} → {output_csv}")


if __name__ == "__main__":
    process_all(
        doc_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dokumen\idn",
        json_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dataset\idn",
        output_score=r"C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2"
    )

=== Memproses direktori: D13-Brain Power ===

Proses D13-Brain Power:   0%|          | 0/12 [00:00<?, ?it/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
Proses D13-Brain Power: 100%|██████████| 12/12 [05:38<00:00, 28.19s/it]

Selesai: D13-Brain Power → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D13-Brain Power.csv

=== Memproses direktori: D14-EmotionalFirstAid ===

Proses D14-EmotionalFirstAid: 100%|██████████| 2/2 [01:48<00:00, 54.48s/it]

Selesai: D14-EmotionalFirstAid → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D14-EmotionalFirstAid.csv

=== Memproses direktori: D15-PsikologiKepribadian ===

Proses D15-PsikologiKepribadian: 100%|██████████| 8/8 [23:38<00:00, 177.35s/it]

Selesai: D15-PsikologiKepribadian → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D15-PsikologiKepribadian.csv

=== Memproses direktori: D16-PsikologiKomunikasi ===

Proses D16-PsikologiKomunikasi: 100%|██████████| 11/11 [12:07<00:00, 66.12s/it]

Selesai: D16-PsikologiKomunikasi → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D16-PsikologiKomunikasi.csv

=== Memproses direktori: D17-Dampak Gadget ===

Proses D17-Dampak Gadget: 100%|██████████| 1/1 [01:12<00:00, 72.11s/it]

Selesai: D17-Dampak Gadget → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D17-Dampak Gadget.csv

=== Memproses direktori: D18-FilosofiTeras ===

Proses D18-FilosofiTeras: 100%|██████████| 11/11 [27:56<00:00, 152.40s/it]

Selesai: D18-FilosofiTeras → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D18-FilosofiTeras.csv

=== Memproses direktori: D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library) ===

Proses D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library):  77%|███████▋  | 17/22 [06:49<01:56, 23.36s/it]Cannot set gray non-stroke color because /'P109' is an invalid float value
Cannot set gray non-stroke color because /'P117' is an invalid float value
Cannot set gray non-stroke color because /'P125' is an invalid float value
Cannot set gray non-stroke color because /'P133' is an invalid float value
Cannot set gray non-stroke color because /'P141' is an invalid float value
Proses D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library): 100%|██████████| 22/22 [08:35<00:00, 23.43s/it]

Selesai: D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library) → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D3-Pengantar Psikologi (Adnan Achiruddin Saleh) (Z-Library).csv

=== Memproses direktori: D4-Pengantar Psikologi Umum (BimoW) ===

Proses D4-Pengantar Psikologi Umum (BimoW): 100%|██████████| 21/21 [12:54<00:00, 36.90s/it]

Selesai: D4-Pengantar Psikologi Umum (BimoW) → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D4-Pengantar Psikologi Umum (BimoW).csv

=== Memproses direktori: D5-MindfullLife ===

Proses D5-MindfullLife: 100%|██████████| 2/2 [00:42<00:00, 21.01s/it]

Selesai: D5-MindfullLife → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D5-MindfullLife.csv

=== Memproses direktori: D7-Seni Menyiksa Diri ===

Proses D7-Seni Menyiksa Diri: 100%|██████████| 6/6 [00:46<00:00,  7.67s/it]

Selesai: D7-Seni Menyiksa Diri → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn2\D7-Seni Menyiksa Diri.csv

## IDN OCR

In [1]:
import os, re, json, math, pdfplumber, torch, csv
import pytesseract
from transformers import AutoTokenizer, AutoModelForSequenceClassification

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"

MODEL_NAME = "facebook/bart-large-mnli"
device = "cuda" if torch.cuda.is_available() else "cpu"
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
model = AutoModelForSequenceClassification.from_pretrained(MODEL_NAME).to(device)
label2id = {v.lower(): k for k, v in model.config.id2label.items()}

In [2]:
import re
import csv
import json
import torch
import pytesseract
from tqdm import tqdm
from pathlib import Path
from pdf2image import convert_from_path

def extract_text_from_scanned_pdf(pdf_path: str) -> str:
    try:
        images = convert_from_path(pdf_path, dpi=300)
        text_list = [pytesseract.image_to_string(img, lang="ind") for img in images]
        return re.sub(r"\s+", " ", "\n".join(text_list)).strip()
    except Exception as e:
        print(f"OCR gagal untuk {pdf_path}: {e}")
        return ""

def chunk_text(txt: str, max_tokens: int = 256, overlap: int = 64):
    words = txt.split()
    step = max_tokens - overlap
    for i in range(0, len(words), step):
        yield " ".join(words[i:i + max_tokens])

@torch.inference_mode()
def nli_score(premise_chunks, hypothesis: str):
    max_scores = {"entailment": 0.0, "neutral": 0.0, "contradiction": 0.0}
    for prem in premise_chunks:
        enc = tokenizer(prem, hypothesis, truncation=True, return_tensors="pt").to(device)
        logits = model(**enc).logits
        probs = torch.softmax(logits, -1)[0]
        for label in max_scores:
            max_scores[label] = max(max_scores[label], probs[label2id[label]].item())
    return max_scores


def extract_range(filename):
    match = re.search(r"(\d{1,3}-\d{1,3})", filename)
    return match.group(1) if match else None


# === Main Otomatisasi Semua Folder ===
def process_all(main_doc_dir: str, main_json_dir: str, output_root: str):
    main_doc_dir = Path(main_doc_dir)
    main_json_dir = Path(main_json_dir)
    output_root = Path(output_root)
    output_root.mkdir(parents=True, exist_ok=True)

    # Loop per subdirektori dokumen
    for doc_subdir in sorted(main_doc_dir.iterdir()):
        if not doc_subdir.is_dir():
            continue

        dir_prefix = doc_subdir.name.split("-")[0]  # contoh: D3
        json_subdir = next((d for d in main_json_dir.iterdir() if d.name.startswith(dir_prefix)), None)

        if not json_subdir:
            print(f"Skip: Tidak ditemukan pasangan folder dataset untuk {doc_subdir.name}")
            continue

        print(f"\n=== Memproses direktori: {doc_subdir.name} ===")

        results = []
        pdf_files = list(doc_subdir.glob("*.pdf"))
        json_files = list(json_subdir.glob("*.json"))

        json_map = {extract_range(f.name): f for f in json_files if extract_range(f.name)}

        for pdf_path in tqdm(pdf_files, desc=f"Proses {doc_subdir.name}"):
            range_key = extract_range(pdf_path.name)
            if not range_key or range_key not in json_map:
                print(f"Skip: {pdf_path.name} tidak ada pasangan JSON cocok.")
                continue

            json_path = json_map[range_key]
            try:
                teks_ocr = extract_text_from_scanned_pdf(str(pdf_path))
                premise_chunks = list(chunk_text(teks_ocr))
                qna_data = json.loads(json_path.read_text(encoding="utf-8"))
                source = "grok" if "grok" in json_path.name.lower() else "gpt"

                for item in qna_data:
                    question = item.get("Question", "").strip()
                    answer = item.get("Answer", "").strip()
                    hypothesis = answer or f"{question} {answer}".strip()
                    scores = nli_score(premise_chunks, hypothesis)

                    results.append({
                        "file": pdf_path.stem,
                        "generator": source,
                        "question": question,
                        "answer": answer,
                        "score_entailment": round(scores["entailment"], 4),
                        "score_neutral": round(scores["neutral"], 4),
                        "score_contradiction": round(scores["contradiction"], 4),
                        "score_final": round(scores["entailment"] - scores["contradiction"], 4)
                    })
            except Exception as e:
                print(f"Gagal memproses {pdf_path.name}: {e}")

        output_csv = output_root / f"{doc_subdir.name}.csv"
        with open(output_csv, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=[
                "file", "generator", "question", "answer",
                "score_entailment", "score_neutral", "score_contradiction", "score_final"
            ], delimiter=";")
            writer.writeheader()
            writer.writerows(results)

        print(f"Selesai: {doc_subdir.name} → {output_csv}")


if __name__ == "__main__":
    pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
    process_all(
        main_doc_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dokumen\idn-ocr",
        main_json_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dataset\idn-ocr",
        output_root=r"C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr2"
    )

=== Memproses direktori: D10-Hidup Damai Tanpa Berpikir Berlebihan ===

Proses D10-Hidup Damai Tanpa Berpikir Berlebihan:   0%|          | 0/13 [00:00<?, ?it/s]Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
Proses D10-Hidup Damai Tanpa Berpikir Berlebihan: 100%|██████████| 13/13 [09:30<00:00, 43.86s/it]

Selesai: D10-Hidup Damai Tanpa Berpikir Berlebihan → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr2\D10-Hidup Damai Tanpa Berpikir Berlebihan.csv

=== Memproses direktori: D6-Berani tidak disukai x Ichiro Kishimi ===

Proses D6-Berani tidak disukai x Ichiro Kishimi: 100%|██████████| 30/30 [12:51<00:00, 25.73s/it]

Selesai: D6-Berani tidak disukai x Ichiro Kishimi → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr2\D6-Berani tidak disukai x Ichiro Kishimi.csv

=== Memproses direktori: D8-Berdamai Dengan Diri Sendiri ===

Proses D8-Berdamai Dengan Diri Sendiri: 100%|██████████| 19/19 [07:47<00:00, 24.61s/it]

Selesai: D8-Berdamai Dengan Diri Sendiri → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr2\D8-Berdamai Dengan Diri Sendiri.csv

=== Memproses direktori: D9-EgoIsTheEnemy ===

Proses D9-EgoIsTheEnemy: 100%|██████████| 24/24 [14:19<00:00, 35.81s/it]

Selesai: D9-EgoIsTheEnemy → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr2\D9-EgoIsTheEnemy.csv

## MARIAN ENG

In [1]:
import os, re, json, csv, math, torch, pytesseract, nltk
from tqdm import tqdm
from pathlib import Path
from pdf2image import convert_from_path
from nltk.tokenize import sent_tokenize
from transformers import (MarianTokenizer, MarianMTModel, AutoTokenizer, AutoModelForSequenceClassification)

pytesseract.pytesseract.tesseract_cmd = r"C:\Program Files\Tesseract-OCR\tesseract.exe"
nltk.download('punkt')
nltk.download('punkt_tab')

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

# === Load Translation Model EN-ID ===
trans_model_name = "Helsinki-NLP/opus-mt-en-id"
trans_tokenizer = MarianTokenizer.from_pretrained(trans_model_name)
trans_model = MarianMTModel.from_pretrained(trans_model_name).to(device)

# === Load NLI Model ===
nli_model_name = "facebook/bart-large-mnli"
nli_tokenizer = AutoTokenizer.from_pretrained(nli_model_name)
nli_model = AutoModelForSequenceClassification.from_pretrained(nli_model_name).to(device)
label2id = {v.lower(): k for k, v in nli_model.config.id2label.items()}

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\Liza\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\Liza\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
c:\Users\Liza\anaconda3\envs\panda\Lib\site-packages\transformers\models\marian\tokenization_marian.py:175: UserWarning: Recommended: pip install sacremoses.
  warnings.warn("Recommended: pip install sacremoses.")

In [2]:
import os
import re
import csv
import json
import torch
from tqdm import tqdm
from pathlib import Path
from pdf2image import convert_from_path
import pytesseract
from nltk.tokenize import sent_tokenize

# === OCR (ENG) ===
def extract_text_from_scanned_pdf(pdf_path: str) -> str:
    print(f"OCR dari: {pdf_path}")
    images = convert_from_path(pdf_path, dpi=300)
    text_list = [pytesseract.image_to_string(img, lang="eng") for img in images]
    return re.sub(r"\s+", " ", "\n".join(text_list)).strip()


# === Translate ENG -> IDN ===
def translate_text(text: str) -> str:
    sentences = sent_tokenize(text)
    translated_sentences = []

    for sentence in tqdm(sentences, desc="Translasi"):
        inputs = trans_tokenizer(sentence, return_tensors="pt", truncation=True, padding=True).to(device)
        outputs = trans_model.generate(**inputs, max_length=512)
        translated = trans_tokenizer.decode(outputs[0], skip_special_tokens=True)
        translated_sentences.append(translated)

    return " ".join(translated_sentences)


# === Potong teks ===
def chunk_text(txt: str, max_tokens: int = 256, overlap: int = 64):
    words = txt.split()
    step = max_tokens - overlap
    for i in range(0, len(words), step):
        yield " ".join(words[i:i + max_tokens])


# === Hitung skor NLI (entailment, neutral, contradiction) ===
@torch.inference_mode()
def nli_score(premise_chunks, hypothesis: str):
    max_scores = {"entailment": 0.0, "neutral": 0.0, "contradiction": 0.0}
    for prem in premise_chunks:
        enc = nli_tokenizer(prem, hypothesis, truncation=True, return_tensors="pt").to(device)
        logits = nli_model(**enc).logits
        probs = torch.softmax(logits, -1)[0]
        for label in max_scores:
            max_scores[label] = max(max_scores[label], probs[label2id[label]].item())
    return {k: round(v, 4) for k, v in max_scores.items()}


def process_all(base_pdf_dir: str, base_json_dir: str, output_dir: str):
    os.makedirs(output_dir, exist_ok=True)

    doc_dirs = [d for d in Path(base_pdf_dir).iterdir() if d.is_dir()]

    for doc_dir in doc_dirs:
        dir_name = doc_dir.name
        json_dir = Path(base_json_dir) / dir_name
        if not json_dir.exists():
            print(f"Tidak ditemukan pasangan dataset untuk {dir_name}")
            continue

        print(f"\n=== Evaluasi direktori: {dir_name} ===")
        results = []

        pdf_files = list(doc_dir.glob("*.pdf"))
        json_files = list(json_dir.glob("*.json"))

        def extract_range(filename):
            match = re.search(r"(\d{1,3}-\d{1,3})", filename)
            return match.group(1) if match else None

        json_map = {extract_range(f.name): f for f in json_files if extract_range(f.name)}

        with tqdm(total=len(pdf_files), desc=f"Evaluasi {dir_name}") as pbar:
            for pdf_path in pdf_files:
                range_key = extract_range(pdf_path.name)
                if not range_key or range_key not in json_map:
                    tqdm.write(f"Tidak menemukan JSON untuk {pdf_path.name}")
                    pbar.update(1)
                    continue

                json_path = json_map[range_key]
                source = "grok" if "grok" in json_path.name.lower() else "gpt"
                tqdm.write(f"\nProses: {pdf_path.name} + {json_path.name}")

                # === OCR + Translate ===
                ocr_text = extract_text_from_scanned_pdf(str(pdf_path))
                id_text = translate_text(ocr_text)
                chunks = list(chunk_text(id_text))

                # === Load dataset JSON ===
                with open(json_path, "r", encoding="utf-8") as f:
                    qna_data = json.load(f)

                # === Evaluasi tiap QnA ===
                for item in qna_data:
                    question = item.get("Question", "").strip()
                    answer = item.get("Answer", "").strip()
                    hypothesis = answer or f"{question} {answer}".strip()

                    scores = nli_score(chunks, hypothesis)

                    results.append({
                        "file": pdf_path.stem,
                        "generator": source,
                        "question": question,
                        "answer": answer,
                        "score_entailment": scores["entailment"],
                        "score_neutral": scores["neutral"],
                        "score_contradiction": scores["contradiction"],
                        "score_final": round(scores["entailment"] - scores["contradiction"], 4)
                    })

                pbar.update(1)

        output_csv = Path(output_dir) / f"{dir_name}.csv"
        with open(output_csv, "w", encoding="utf-8", newline="") as f:
            writer = csv.DictWriter(f, fieldnames=[
               "file", "generator", "question", "answer",
                "score_entailment", "score_neutral", "score_contradiction", "score_final"
            ], delimiter=";")
            writer.writeheader()
            writer.writerows(results)

        print(f"Selesai: {output_csv}")


if __name__ == "__main__":
    process_all(
        base_pdf_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng",
        base_json_dir=r"C:\Users\Liza\Documents\Kerja Praktik\dataset\eng",
        output_dir=r"C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\eng2"
    )

=== Evaluasi direktori: D1-Health Psychology, 9th Ed (Shelley E. Taylor) ===

Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):   0%|          | 0/10 [00:00<?, ?it/s]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-1-55.pdf + D1_GROK_HealthPsycology1-55_67.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-1-55.pdf

Translasi: 100%|██████████| 1118/1118 [04:44<00:00,  3.93it/s]
Passing a tuple of `past_key_values` is deprecated and will be removed in Transformers v4.58.0. You should pass an instance of `EncoderDecoderCache` instead, e.g. `past_key_values=EncoderDecoderCache.from_legacy_cache(past_key_values)`.
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  10%|█         | 1/10 [23:06<3:28:00, 1386.69s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-114-151.pdf + D1_GROK_HealthPsycology114-151_58.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-114-151.pdf

Translasi: 100%|██████████| 929/929 [03:29<00:00,  4.44it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  20%|██        | 2/10 [40:33<2:38:13, 1186.69s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-152-167.pdf + D1_GPT_HealthPsycology152-167_50.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-152-167.pdf

Translasi: 100%|██████████| 440/440 [01:31<00:00,  4.79it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  30%|███       | 3/10 [46:35<1:34:31, 810.18s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-168-183.pdf + D1_GPT_HealthPsycology168-183_30.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-168-183.pdf

Translasi: 100%|██████████| 395/395 [01:27<00:00,  4.53it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  40%|████      | 4/10 [51:05<59:40, 596.81s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-184-208.pdf + D1_GPT_HealthPsycology184-208_50.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-184-208.pdf

Translasi: 100%|██████████| 741/741 [02:26<00:00,  5.06it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  50%|█████     | 5/10 [1:01:15<50:08, 601.68s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-209-229.pdf + D1_GPT_HealthPsycology209-229_50.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-209-229.pdf

Translasi: 100%|██████████| 549/549 [01:59<00:00,  4.58it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  60%|██████    | 6/10 [1:08:49<36:45, 551.42s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-230-249.pdf + D1_GROK_HealthPsycology230-249_50.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-230-249.pdf

Translasi: 100%|██████████| 486/486 [01:57<00:00,  4.14it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  70%|███████   | 7/10 [1:16:04<25:40, 513.54s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-250-268.pdf + D1_GPT_HealthPsycology250-268_50.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-250-268.pdf

Translasi: 100%|██████████| 513/513 [01:57<00:00,  4.37it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  80%|████████  | 8/10 [1:23:44<16:32, 496.44s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-56-95.pdf + D1_GROK_HealthPsycology56-95_67.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-56-95.pdf

Translasi: 100%|██████████| 950/950 [04:04<00:00,  3.89it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor):  90%|█████████ | 9/10 [1:45:13<12:24, 744.15s/it]

Proses: Health Psychology, 9th Ed (Shelley E. Taylor)-96-113.pdf + D1_GROK_HealthPsycology96-113_30.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D1-Health Psychology, 9th Ed (Shelley E. Taylor)\Health Psychology, 9th Ed (Shelley E. Taylor)-96-113.pdf

Translasi: 100%|██████████| 443/443 [01:48<00:00,  4.09it/s]
Evaluasi D1-Health Psychology, 9th Ed (Shelley E. Taylor): 100%|██████████| 10/10 [1:51:36<00:00, 669.64s/it]

Selesai: C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\eng2\D1-Health Psychology, 9th Ed (Shelley E. Taylor).csv

=== Evaluasi direktori: D11-A Handbook for the Study of Mental Health Social ===

Evaluasi D11-A Handbook for the Study of Mental Health Social:   0%|          | 0/54 [00:00<?, ?it/s]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-105-115.pdf + D11_GROK_AHandbookfortheSMH105-115_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-105-115.pdf

Translasi: 100%|██████████| 232/232 [00:44<00:00,  5.23it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:   2%|▏         | 1/54 [01:54<1:41:30, 114.92s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-116-126.pdf + D11_GROK_AHandbookfortheSMH116-126_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-116-126.pdf

Translasi: 100%|██████████| 274/274 [00:48<00:00,  5.68it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:   4%|▎         | 2/54 [04:00<1:44:59, 121.15s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-127-137.pdf + D11_GROK_AHandbookfortheSMH127-137_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-127-137.pdf

Translasi: 100%|██████████| 177/177 [00:44<00:00,  3.94it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:   6%|▌         | 3/54 [06:00<1:42:34, 120.69s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-138-148.pdf + D11_GROK_AHandbookfortheSMH138-148_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-138-148.pdf

Translasi: 100%|██████████| 176/176 [00:47<00:00,  3.70it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:   7%|▋         | 4/54 [08:06<1:42:19, 122.78s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-149-159.pdf + D11_GROK_AHandbookfortheSMH149-159_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-149-159.pdf

Translasi: 100%|██████████| 152/152 [00:39<00:00,  3.82it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:   9%|▉         | 5/54 [09:50<1:34:47, 116.08s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-160-170.pdf + D11_GROK_AHandbookfortheSMH160-170_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-160-170.pdf

Translasi: 100%|██████████| 181/181 [00:47<00:00,  3.80it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  11%|█         | 6/54 [11:51<1:34:04, 117.59s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-17-27.pdf + D11_GROK_AHandbookfortheSMH17-27_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-17-27.pdf

Translasi: 100%|██████████| 130/130 [00:32<00:00,  3.98it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  13%|█▎        | 7/54 [13:18<1:24:15, 107.55s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-171-181.pdf + D11_GROK_AHandbookfortheSMH171-181_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-171-181.pdf

Translasi: 100%|██████████| 189/189 [00:48<00:00,  3.89it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  15%|█▍        | 8/54 [15:18<1:25:33, 111.61s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-182-192.pdf + D11_GROK_AHandbookfortheSMH182-192_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-182-192.pdf

Translasi: 100%|██████████| 151/151 [00:38<00:00,  3.91it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  17%|█▋        | 9/54 [17:02<1:21:50, 109.12s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-193-203.pdf + D11_GROK_AHandbookfortheSMH193-203_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-193-203.pdf

Translasi: 100%|██████████| 161/161 [00:49<00:00,  3.27it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  19%|█▊        | 10/54 [19:01<1:22:14, 112.15s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-204-214.pdf + D11_GROK_AHandbookfortheSMH204-214_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-204-214.pdf

Translasi: 100%|██████████| 171/171 [00:45<00:00,  3.77it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  20%|██        | 11/54 [20:57<1:21:17, 113.44s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-215-225.pdf + D11_GROK_AHandbookfortheSMH215-225_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-215-225.pdf

Translasi: 100%|██████████| 132/132 [00:40<00:00,  3.25it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  22%|██▏       | 12/54 [22:42<1:17:32, 110.78s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-226-236.pdf + D11_GROK_AHandbookfortheSMH226-236_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-226-236.pdf

Translasi: 100%|██████████| 172/172 [00:44<00:00,  3.88it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  24%|██▍       | 13/54 [24:38<1:16:50, 112.45s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-237-247.pdf + D11_GROK_AHandbookfortheSMH237-247_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-237-247.pdf

Translasi: 100%|██████████| 183/183 [00:46<00:00,  3.89it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  26%|██▌       | 14/54 [26:44<1:17:46, 116.67s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-248-258.pdf + D11_GROK_AHandbookfortheSMH248-258_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-248-258.pdf

Translasi: 100%|██████████| 196/196 [00:48<00:00,  4.07it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  28%|██▊       | 15/54 [28:50<1:17:35, 119.38s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-259-269.pdf + D11_GROK_AHandbookfortheSMH259-269_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-259-269.pdf

Translasi: 100%|██████████| 179/179 [00:43<00:00,  4.16it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  30%|██▉       | 16/54 [30:39<1:13:36, 116.22s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-270-280.pdf + D11_GROK_AHandbookfortheSMH270-280_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-270-280.pdf

Translasi: 100%|██████████| 191/191 [00:43<00:00,  4.34it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  31%|███▏      | 17/54 [32:34<1:11:33, 116.05s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-28-38.pdf + D11_GROK_AHandbookfortheSMH28-38_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-28-38.pdf

Translasi: 100%|██████████| 205/205 [00:45<00:00,  4.54it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  33%|███▎      | 18/54 [34:37<1:10:50, 118.07s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-281-291.pdf + D11_GROK_AHandbookfortheSMH281-291_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-281-291.pdf

Translasi: 100%|██████████| 214/214 [00:48<00:00,  4.40it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  35%|███▌      | 19/54 [36:41<1:09:49, 119.70s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-292-302.pdf + D11_GROK_AHandbookfortheSMH292-302_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-292-302.pdf

Translasi: 100%|██████████| 206/206 [00:48<00:00,  4.24it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  37%|███▋      | 20/54 [38:39<1:07:33, 119.21s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-303-313.pdf + D11_GROK_AHandbookfortheSMH303-313_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-303-313.pdf

Translasi: 100%|██████████| 190/190 [00:52<00:00,  3.61it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  39%|███▉      | 21/54 [40:44<1:06:35, 121.09s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-314-324.pdf + D11_GROK_AHandbookfortheSMH314-324_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-314-324.pdf

Translasi: 100%|██████████| 162/162 [00:53<00:00,  3.02it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  41%|████      | 22/54 [42:51<1:05:26, 122.69s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-325-335.pdf + D11_GROK_AHandbookfortheSMH325-335_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-325-335.pdf

Translasi: 100%|██████████| 168/168 [00:49<00:00,  3.40it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  43%|████▎     | 23/54 [44:51<1:03:04, 122.09s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-336-346.pdf + D11_GROK_AHandbookfortheSMH336-346_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-336-346.pdf

Translasi: 100%|██████████| 177/177 [00:45<00:00,  3.86it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  44%|████▍     | 24/54 [46:58<1:01:40, 123.35s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-347-357.pdf + D11_GROK_AHandbookfortheSMH347-357_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-347-357.pdf

Translasi: 100%|██████████| 161/161 [00:44<00:00,  3.63it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  46%|████▋     | 25/54 [48:59<59:17, 122.68s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-358-368.pdf + D11_GROK_AHandbookfortheSMH358-368_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-358-368.pdf

Translasi: 100%|██████████| 145/145 [00:45<00:00,  3.22it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  48%|████▊     | 26/54 [50:46<55:03, 117.99s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-369-379.pdf + D11_GROK_AHandbookfortheSMH369-379_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-369-379.pdf

Translasi: 100%|██████████| 196/196 [00:46<00:00,  4.22it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  50%|█████     | 27/54 [52:53<54:19, 120.71s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-380-390.pdf + D11_GROK_AHandbookfortheSMH380-390_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-380-390.pdf

Translasi: 100%|██████████| 240/240 [00:49<00:00,  4.81it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  52%|█████▏    | 28/54 [54:52<52:02, 120.08s/it]

Proses: A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-39-49.pdf + D11_GROK_AHandbookfortheSMH39-49_20.json
OCR dari: C:\Users\Liza\Documents\Kerja Praktik\dokumen\eng\D11-A Handbook for the Study of Mental Health Social\A Handbook for the Study of Mental Health Social Contexts, Theories, and Systems (Teresa L. Scheid, Tony N. Brown) (z-lib.org)-39-49.pdf

Translasi: 100%|██████████| 163/163 [00:44<00:00,  3.70it/s]
Evaluasi D11-A Handbook for the Study of Mental Health Social:  52%|█████▏    | 28/54 [56:08<52:07, 120.29s/it]

KeyboardInterrupt:

In [6]:
import os
import pandas as pd

base_dir = r"C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score"
folders = ["eng", "idn", "idn-ocr"]

merged_dfs = {}

def safe_read_csv(csv_file, expected_cols=None):
    """
    Membaca CSV dengan berbagai fallback agar tetap bisa diparse
    meskipun formatnya tidak konsisten.
    """
    df = None
    try:
        # Coba normal dulu (auto-deteksi delimiter)
        df = pd.read_csv(csv_file, sep=None, engine="python", encoding="utf-8-sig", quotechar='"')
    except Exception as e1:
        print(f"Error baca {csv_file}: {e1}")

        try:
            # Coba pakai koma eksplisit
            df = pd.read_csv(csv_file, sep=",", quotechar='"', engine="python", encoding="utf-8-sig")
        except Exception as e2:
            print(f"Fallback kedua gagal: {e2}")
            try:
                # Fallback terakhir: parsing manual per baris
                with open(csv_file, "r", encoding="utf-8-sig", errors="replace") as f:
                    lines = [line.strip() for line in f if line.strip()]
                rows = []
                for line in lines:
                    parts = []
                    current = ""
                    in_quotes = False
                    for char in line:
                        if char == '"':
                            in_quotes = not in_quotes
                        elif char == "," and not in_quotes:
                            parts.append(current)
                            current = ""
                        else:
                            current += char
                    parts.append(current)
                    rows.append(parts)

                max_cols = max(len(r) for r in rows)
                df = pd.DataFrame(rows, columns=[f"col_{i}" for i in range(max_cols)])
                print(f"Dibaca pakai parser manual: {csv_file} ({max_cols} kolom)")
            except Exception as e3:
                print(f"Gagal total baca {csv_file}: {e3}")
                return pd.DataFrame()

    # Samakan jumlah kolom antar file
    if expected_cols is not None:
        for col in expected_cols:
            if col not in df.columns:
                df[col] = None
        df = df[expected_cols]

    return df


for folder in folders:
    folder_path = os.path.join(base_dir, folder)
    all_csv_files = []

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith(".csv"):
                all_csv_files.append(os.path.join(root, file))

    if not all_csv_files:
        print(f"Tidak ada file CSV di {folder}")
        continue

    print(f"\nMemproses folder: {folder}")
    first_df = safe_read_csv(all_csv_files[0])
    expected_cols = list(first_df.columns)
    dfs = [first_df]

    for csv_file in all_csv_files[1:]:
        df = safe_read_csv(csv_file, expected_cols)
        dfs.append(df)

    combined_df = pd.concat(dfs, ignore_index=True)
    combined_df = combined_df.dropna(how="all")  # hapus baris kosong

    output_path = os.path.join(base_dir, f"{folder}_all.csv")
    combined_df.to_csv(output_path, index=False, encoding="utf-8-sig")

    merged_dfs[folder] = combined_df
    print(f"{folder}: {len(dfs)} file digabung → {output_path}")

# Gabungkan semua folder
if merged_dfs:
    final_df = pd.concat(merged_dfs.values(), ignore_index=True, sort=False)
    final_path = os.path.join(base_dir, "final_score_NLI.csv")
    final_df.to_csv(final_path, index=False, encoding="utf-8-sig")
    print(f"\nSemua selesai. File akhir disimpan di:\n{final_path}")
else:
    print("Tidak ada file CSV valid yang ditemukan untuk digabungkan.")

Memproses folder: eng
eng: 4 file digabung → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\eng_all.csv

Memproses folder: idn
Error baca C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn\D15-PsikologiKepribadian.csv: ',' expected after '"'
Fallback kedua gagal: ',' expected after '"'
Dibaca pakai parser manual: C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn\D15-PsikologiKepribadian.csv (8 kolom)
idn: 10 file digabung → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn_all.csv

Memproses folder: idn-ocr
idn-ocr: 4 file digabung → C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\idn-ocr_all.csv

Semua selesai. File akhir disimpan di:
C:\Users\Liza\Documents\Kerja Praktik\NLI\Hasil score\final_score_NLI.csv

C:\Users\Liza\AppData\Local\Temp\ipykernel_11864\744678218.py:85: FutureWarning: The behavior of DataFrame concatenation with empty or all-NA entries is deprecated. In a future version, this will no longer exclude empty or all-NA columns when determining the result dtypes. To retain the old behavior, exclude the relevant entries before the concat operation.
  combined_df = pd.concat(dfs, ignore_index=True)

In [14]:
import pandas as pd

# Baca ulang CSV dengan delimiter yang benar
df = pd.read_csv("Hasil score/idn-ocr_all.csv")
df

,file,generator,question,answer,score_entailment,score_neutral,score_contradiction,score_final
0,Hidup Damai Tanpa Berpikir Berlebihan x Tsunek...,grok,Aku merasa tertekan banget kalau kerjaan menum...,Wajar kok merasa tertekan kalau kerjaan numpuk...,0.8699,0.2814,0.2496,0.6203
1,Hidup Damai Tanpa Berpikir Berlebihan x Tsunek...,grok,Kadang aku ragu bisa nggak ya ngerjain tugas y...,"Ragu itu manusiawi banget. Coba aja dulu, angg...",0.7990,0.2718,0.4013,0.3977
2,Hidup Damai Tanpa Berpikir Berlebihan x Tsunek...,grok,"Aku takut gagal kalau coba sesuatu yang baru, ...","Takut gagal itu normal, kok. Tapi coba pikir, ...",0.8063,0.3049,0.4347,0.3715
3,Hidup Damai Tanpa Berpikir Berlebihan x Tsunek...,grok,"Aku sering kurang tidur karena kerja, ini buru...","Wah, kurang tidur itu bisa bikin tubuh dan pik...",0.7062,0.2959,0.4438,0.2623
4,Hidup Damai Tanpa Berpikir Berlebihan x Tsunek...,grok,Aku pengen kerja keras terus biar dianggap heb...,"Nggak salah pengen berprestasi, tapi kalau sam...",0.7865,0.2849,0.4542,0.3324
...,...,...,...,...,...,...,...,...
1524,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku kesal banget sama rekan kerja yang selalu ...,"Kesal itu wajar, tapi kasih pelajaran langsung...",0.9044,0.2464,0.6489,0.2556
1525,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku merasa nggak cukup baik dibandingkan orang...,"Perasaan itu sering datang, tapi coba ingat: k...",0.8270,0.3752,0.4388,0.3882
1526,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku pengen ngeluh terus kalau kerjaan nggak ad...,"Ngeluh sesekali boleh, tapi kalau terus-terusa...",0.8327,0.2022,0.6467,0.1860
1527,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku merasa orang lain nggak pantas dapat posis...,"Wajar kalau merasa kecewa, tapi fokus ke orang...",0.9241,0.2168,0.6458,0.2783
1528,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku takut gagal kalau coba hal baru. Apa aku h...,"Takut gagal itu normal, tapi zona nyaman bisa ...",0.8278,0.1587,0.6340,0.1938

In [15]:
df.isna().any()

file                   False
generator              False
question                True
answer                  True
score_entailment       False
score_neutral          False
score_contradiction    False
score_final            False
dtype: bool

In [16]:
df[df['question'].isna() | df['answer'].isna()]

,file,generator,question,answer,score_entailment,score_neutral,score_contradiction,score_final
540,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
541,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
542,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
543,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
544,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
545,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
546,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
547,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
548,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
549,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
550,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
551,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
552,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028
553,Berani tidak disukai x Ichiro Kishimi Dan Fumi...,grok,NaN,NaN,0.8643,0.4493,0.8615,0.0028

In [21]:
df.describe(include='all')

,file,generator,question,answer,entailment,neutral,contradiction,score
count,3443,3443,3443,3443,3443.000000,3443.000000,3443.000000,3443.000000
unique,144,2,3438,3443,NaN,NaN,NaN,NaN
top,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,Aku ngerasa hidupku nggak ada artinya. Apa aku...,"Tentu, saya paham kalau istilah ini bisa teras...",NaN,NaN,NaN,NaN
freq,70,3151,2,1,NaN,NaN,NaN,NaN
mean,NaN,NaN,NaN,NaN,0.867640,0.262558,0.466867,0.400773
std,NaN,NaN,NaN,NaN,0.070872,0.087365,0.149960,0.190984
min,NaN,NaN,NaN,NaN,0.383000,0.073400,0.085500,-0.357100
25%,NaN,NaN,NaN,NaN,0.829400,0.206250,0.358100,0.274800
50%,NaN,NaN,NaN,NaN,0.879600,0.246500,0.455700,0.413700
75%,NaN,NaN,NaN,NaN,0.919100,0.296500,0.569450,0.538350
max,NaN,NaN,NaN,NaN,0.989300,0.925800,0.948900,0.885600

In [6]:
import pandas as pd

df = pd.read_csv(r"Hasil score\score_nli_result.csv", sep=';')
df

,file,generator,question,answer,score_entailment,score_neutral,score_contradiction,score_final
0,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,Saya merasa bingung tentang apa itu kesehatan ...,"Tentu, saya paham kalau istilah ini bisa teras...",0.9724,0.2708,0.2997,0.6727
1,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,Saya sering merasa kesehatan saya dipengaruhi ...,Keren banget kamu peka sama tubuh dan pikiranm...,0.9827,0.2300,0.3361,0.6466
2,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,"Akhir-akhir ini saya merasa stres berat, dan t...","Wah, saya tahu rasanya saat stres bikin semuan...",0.9030,0.2509,0.6111,0.2919
3,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,"Saya merasa sendiri akhir-akhir ini, dan itu b...","Aduh, rasanya pasti nggak enak kalau merasa se...",0.9556,0.3639,0.5771,0.3785
4,"Health Psychology, 9th Ed (Shelley E. Taylor)-...",grok,Saya sering merasa kewalahan saat menghadapi m...,"Saya paham, kadang masalah terasa seperti gunu...",0.9218,0.2387,0.5177,0.4041
...,...,...,...,...,...,...,...,...
7495,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku kesal banget sama rekan kerja yang selalu ...,"Kesal itu wajar, tapi kasih pelajaran langsung...",0.9044,0.2464,0.6489,0.2556
7496,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku merasa nggak cukup baik dibandingkan orang...,"Perasaan itu sering datang, tapi coba ingat: k...",0.8270,0.3752,0.4388,0.3882
7497,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku pengen ngeluh terus kalau kerjaan nggak ad...,"Ngeluh sesekali boleh, tapi kalau terus-terusa...",0.8327,0.2022,0.6467,0.1860
7498,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku merasa orang lain nggak pantas dapat posis...,"Wajar kalau merasa kecewa, tapi fokus ke orang...",0.9241,0.2168,0.6458,0.2783
7499,Ego is the Enemy - Ryan Holiday-94-105,grok,Aku takut gagal kalau coba hal baru. Apa aku h...,"Takut gagal itu normal, tapi zona nyaman bisa ...",0.8278,0.1587,0.6340,0.1938

In [8]:
df.describe()

       score_entailment  score_neutral  score_contradiction  score_final
count       7500.000000    7500.000000          7500.000000  7500.000000
mean           0.847825       0.247116             0.460885     0.386940
std            0.086240       0.085581             0.157506     0.202914
min            0.282300       0.059500             0.036300    -0.699800
25%            0.801700       0.192975             0.344600     0.253000
50%            0.865000       0.233500             0.450550     0.401750
75%            0.911525       0.282525             0.570100     0.530825
max            0.989300       0.925800             0.982000     0.922500